### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by SamArtGit** [iOrange/bumpx#1]
Привет iOrange, решил не засорять личку. А можно сделать так, чтобы из имеющихся bump и bump# преобразовывало обратно в nrm? Потому-что если просто брать bump и менять каналы цветов в нужном порядке, то остаются ошибки сжатия, которые исправляются в bump#. А как смешивать bump и bump# в том же Photoshop, не имею представления.

**Comment by iOrange** [comment]
> Привет iOrange, решил не засорять личку. А можно сделать так, чтобы из имеющихся bump и bump# преобразовывало обратно в nrm? Потому-что если просто брать bump и менять каналы цветов в нужном порядке, то остаются ошибки сжатия, которые исправляются в bump#. А как смешивать bump и bump# в том же Photoshop, не имею представления.

Привет. В принципе можно.  Если не забуду - постараюсь на этой неделе запилить.

**Comment by iOrange** [comment]
Выполнено в 33261b0466e5830ba12b367cbd08b45304378a7c
